/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package basic.demo

//import kotlin.test.Test
import kotlin.test.assertTrue
import kotlin.test.assertNotNull

import com.nhaarman.mockitokotlin2.*
import com.nhaarman.expect.expect

import org.spekframework.spek2.Spek
import org.spekframework.spek2.style.specification.describe

object AppSpec: Spek({

  describe("app") {

    val classUnderTest by memoized { App() }

    it("should pass") {
        assertTrue(true)
    }

    it("should have a greeting") {
        assertNotNull(classUnderTest.greeting)
    }
  }
})
