/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package basic.demo

//import kotlin.test.Test
//import kotlin.test.assertNotNull

import com.nhaarman.mockitokotlin2.*
import com.nhaarman.expect.expect

import org.spekframework.spek2.Spek
import org.spekframework.spek2.style.specification.describe
import org.junit.jupiter.api.Assertions as test

object AppSpec: Spek({

  describe("app") {

    val classUnderTest by memoized { App() }

    it("should pass") {
        test.assertTrue(true)
    }

    it("should have a greeting") {
        test.assertNotNull(classUnderTest.greeting)
    }
  }
})
